export const translations = {
  en: {
    settings: "Settings",
    language: "Language",
    notifications: "Notifications",
    version: "App Version",
    logout: "Logout",
    editDriver: "Edit Driver",
    name: "Name",
    phone: "Phone",
    status: "Status",
    route: "Route",
    checkpoint: "Checkpoint",
    selectStatus: "Select Status",
    selectRoute: "Select Route",
    selectCheckpoint: "Select Checkpoint",
    save: "Save",
    saving: "Saving...",
    hi: "Hi",
    welcome: "Welcome",
    summaryText: "Here is your trip summary.",
    new: "New",
    active: "Active",
    done: "Done",
    trip:"Trip",
    latestTrips: "Latest Trips",
    viewAllTrips: "View All Trips",
    all: "All",
    unread: "Unread",
    read: "Read",
    pushNotifications: "Push Notifications",
    markAllRead: "Mark All as Read",
    deleteAll: "Delete All",
    myTrips: "My Trips",
    ongoing: "Ongoing",
    completed: "Completed",
    noTrips: "No trips found",
    created: "Created",
    viewTrip: "View Trip",
    tripDetail: "Trip Detail",
    tripId: "Trip ID",
    truck: "Truck",
    driver: "Driver",
    createdAt: "Created At",
    containers: "Containers",
    noContainers: "No containers assigned",
    type: "Type",
    updateStatus: "Update Status",
    na: "N/A",
    containerDetail: "Container Detail",
    basicInfo: "Basic Information",
    pickupInfo: "Pickup Information",
    deliveryInfo: "Delivery Information",
    billingRemark: "Billing & Remark",
    attachments: "Attachments",
    containerNo: "Container No.",
    productCategory: "Product Category",
    pickupDate: "Pickup Date",
    pickupAddress: "Pickup Address",
    pickupPerson: "Pickup Contact Person",
    pickupPhone: "Pickup Contact Phone",
    deliveryAddress: "Delivery Address",
    deliveryPerson: "Delivery Contact Person",
    deliveryPhone: "Delivery Contact Phone",
    billingCustomer: "Billing Customer",
    remark: "Remark",
    noAttachments: "No attachments available",
    previewNotAvailable: "Preview not available",
    downloadFile: "Download File",
    update_trip_status: "Update Trip Status",
    trip_id: "Trip ID",
    current_stage: "Current Stage",
    select_next_stage: "Select Next Stage",
    notes: "Notes...",
    latitude: "Latitude",
    longitude: "Longitude",
    expenses: "Expenses",
    add_expense: "Add Expense",
    title: "Title",
    note: "Note",
    amount: "Amount",
    save_expense: "Save Expense",
    cancel: "Cancel",
    no_expenses: "No expenses added",
    remove: "Remove",
    upload_save: "Upload & Save",
    back_trip: "Back to Trip Detail",
    login: "Login",
    logging_in: "Logging in...",
    enter_username:"Enter Username",
    enter_password:"Enter Password",
    password: "Password",
    remember: "Remember Me",
    forgot_password: "Forgot Password?",
    search_expense_type:"Search Expense Type...",
  },
  th: {
    settings: "ตั้งค่า",
    language: "ภาษา",
    notifications: "การแจ้งเตือน",
    version: "เวอร์ชั่นของแอป",
    logout: "ออกจากระบบ",
    editDriver: "แก้ไขคนขับ",
    name: "ชื่อ",
    phone: "โทรศัพท์",
    status: "สถานะ",
    route: "เส้นทาง",
    checkpoint: "จุดตรวจ",
    selectStatus: "เลือกสถานะ",
    selectRoute: "เลือกเส้นทาง",
    selectCheckpoint: "เลือกจุดตรวจ",
    save: "บันทึก",
    hi: "สวัสดี",
    welcome: "ยินดีต้อนรับ",
    summaryText: "สรุปข้อมูลรถ",
    new: "ใหม่",
    active: "ใช้งานอยู่",
    done: "เสร็จสิ้น",
    trip:"ตรวจสอบข้อมููล",
    latestTrips: "ตรวจสอบข้อมูลล่าสุด",
    viewAllTrips: "ตรวจสอบข้อมูลทั้งหมด",
    all: "ทั้งหมด",
    unread: "ยังไม่ได้อ่าน",
    read: "อ่านแล้ว",
    pushNotifications: "การแจ้งเตือนแบบพุช",
    markAllRead: "ทำเครื่องหมายว่าอ่านทั้งหมด",
    deleteAll: "ลบทั้งหมด",
    myTrips: "การตรวจสอบข้อมูลของฉัน",
    ongoing: "กำลังไป",
    completed: "สำเร็จ",
    noTrips: "ตรวจสอบไม่พบข้อมูล",
    created: "โครงสร้าง",
    viewTrip: "ดูการตรวจสอบช้อมูล",
    tripDetail: "ตรวจสอบรายละเอียดข้อมูล",
    tripId: "รหัสงาน",
    truck: "รถบรรทุก",
    driver: "คนขับ",
    createdAt: "โครงสร้าง",
    containers: "ตู้คอนเทนเนอร์",
    noContainers: "ไม่มีตู้คอนเทนเนอร์",
    type: "ประเภท",
    updateStatus: "อัปเดตสถานะ",
    na: "ไม่มีข้อมูล",
    containerDetail: "รายละเอียดตู้คอนเทนเนอร์",
    basicInfo: "ข้อมูลพื้นฐาน",
    pickupInfo: "ข้อมูลการรับสินค้า",
    deliveryInfo: "ข้อมูล ส่งสินค้า",
    billingRemark: "หมายเหตุการเก็บเงิน",
    attachments: "เอกสารแนบ",
    containerNo: "เลขตู้คอนเทนเนอร์",
    productCategory: "หมวดหมู่สินค้า",
    pickupDate: "วันที่รับสินค้า",
    pickupAddress: "ที่อยู่รับสินค้า",
    pickupPerson: "ข้อมูลผู้ติดต่อรับสินค้า",
    pickupPhone: "เบอร์ผู้ติดต่อรับสินค้า",
    deliveryAddress: "ที่ี่อยู่สำหรับส่งสินค้า",
    deliveryPerson: "ผู้ติดต่อสำหรับส่งสินค้า",
    deliveryPhone: "เบอร์ผู้ติดต่อสำหรับส่งสินค้า",
    billingCustomer: "การเก็บเงินลูกค้า",
    remark: "หมายเหตุ",
    noAttachments: "ไม่มีไฟล์แนบ",
    previewNotAvailable: "ไม่สามารถแสดงตัวอย่างได้",
    downloadFile: "ดาวน์โหลดไฟล์",
    update_trip_status: "อัปเดตสถานะข้อมูล",
    trip_id: "ตรวจสอบไอดี",
    current_stage: "สถานะปัจจุบัน",
    select_next_stage: "เลือกขั้นตอนถัดไป",
    notes: "หมายเหตุ",
    latitude: "ละติจูด",
    longitude: "ลองจิจูด",
    expenses: "ค่าใช้จ่าย",
    add_expense: "เพิ่มค่าใช้จ่าย",
    title: "ชื่อ",
    note: "หมายเหตุ",
    amount: "จำนวน",
    save_expense: "บันทึกค่าใช้จ่าย",
    cancel: "ยกเลิก",
    no_expenses: "ไม่มีค่าใช้จ่ายเพิ่ม",
    remove: "ลบ",
    saving: "กำลังบันทึก...",
    upload_save: "อัปโหลดและบันทึก",
    back_trip: "กลับไปหน้ารายละเอียด",
    login: "เข้าสู่ระบบ",
    logging_in: "กำลังเข้าสู่ระบบ...",
    enter_username:"ป้อนชื่อผู้ใช้",
    enter_password:"รหัสผ่าน",
    password: "รหัสผ่าน",
    remember: "จดจำรหัสผ่าน",
    forgot_password: "ลืมรหัสผ่าน?",
    search_expense_type:"ค้นหาค่าใช้จ่าย",
  }
};
