export const translations = {
    en: {
        dashboard: "Dashboard",
        myCustomers: "My Customers",
        allCustomers: "All Customers",
        customerExpirations: "Customer Expirations",
        customerExpiryThisMonth:"Customer Expirations this Month",
        newCustomersThisMonth: "New Customers this Month",
        activeServiceActivity: "Active Service Activities",
        uploadFromExcel: "Upload from Excel",
        myServices: "My Services",
        allServices: "All Services",
        createService: "Create Service",
        createCustomer: "Create Customer",
        pleaseTypeCustomerId: "Please type customer id",
        customerId: "Customer ID",
        nameEng: "Name (Eng)",
        nameMm: "Name (MM)",
        nrcNo: "Nrc No.",
        prevPassportNo: "Previous Passport No.",
        passportNo: "Passport No.",
        passportExpiryDate: "Passport Expiry Date",
        visaType: "Visa Type",
        visaNumber: "Visa Number",
        visaExpiryDate: "Visa Expiry Date",
        detail: "Detail",
        view: "View",
        search: "Search",
        addNewCustomer: "Add New Customer",
        sex: "Sex",
        dob: "D.O.B",
        nrc: "Nrc",
        nationality: "Nationality",
        passportDetails: "Passport Details",
        scanPassport: "Scan Passport",
        visaDetails: "Visa Details",
        scanVisa: "Scan Visa",
        ciDetails: "CI Details",
        scanCi: "Scan CI",
        ciNo: "CI No.",
        ciExpiryDate: "CI Expiry Date",
        pinkCardDetails: "Pink Card Details",
        scanPinkCard: "Scan Pink Card",
        pinkCardNo: "Pink Card No.",
        pinkCardExpiryDate: "Pink Card Expiry Date",
        phonePrimary: "Phone No. (Primary)",
        phoneSecondary: "Phone No. (Secondary)",
        emailAddress: "E-mail Address",
        currentAddress: "Current Address",
        save: "Save",
        saving: 'Saving...',
        back: "Back",
        editCustomer: "Edit Customer",
        passportExpiry: "Passport Expiry",
        visaExpiry: "Visa Expiry",
        pinkCardExpiry: "Pink Card Expiry",
        ciCardExpiry: "CI Card Expiry",
        addServiceActivity: "Add Service Activity",
        status: "Status",
        serviceRequestType: "Service Request Type",
        refresh: "Refresh",
        requestDate: "Request Date",
        requestBy: "Request By",
        chooseCustomer: "Choose Customer",
        requestType: "Request Type",
        serviceStatus: "Service Status",
        customerServiceUrl: "Customer Service URL",
        copy: "Copy",
        send: "Send",
        createServiceActivity:"Create Service Activity",
        editServiceActivity: "Edit Service Activity",
        importCustomers: "Import Customers",
        uploadFile: "Upload File",
        format: "Format",
        cancel: "Cancel",
        import: "Import",
        importing: 'Importing...',
        bizName: "Biz Name",
        phoneNumber: "Phone Number",
        location: "Location",
        availableServices: "Available Services",
        category: "Category",
        title: "Title",
        serviceCost: "Service Cost",
        serviceDuration: "Service Duration",
        editService: "Edit Service",
        agentId: "Agent ID",
        userSetting: "User Setting",
        logout: "Logout",
        name: "Name",
        email: "Email",
        password: "Password",
        confirmPassword: "Confirm Password",
        updateProfile: "Update Profile",
        leaveBlankPassword: "Leave blank to keep current password",
        editProfile: "Edit Profile",
        setup: "Setup",
        management: "Management",
        categories: "Categories",
        roles: "Roles",
        users: "Users",
        agents: "Agents",
        addAgent: "Add Agent",
        createAgent: "Create Agent",
        editAgent: "Edit Agent",
        addCategory: "Add Category",
        createCategory: "Create Category",
        editCategory: "Edit Category",
        addUser: "Add User",
        createUser: "Create Agent",
        editUser: "Edit User",
        addRole: "Add Role",
        createRole: "Create Role",
        editRole: "Edit Role",
        totalAgents: "Total Agents",
        agentsThisMonth: "Agents this month",
        totalCustomers: "Total Customers",
        customersThisMonth: "Customers this month",
        language: "Language",
        welcomeEpsSystem: "Logistic",
        login: "Login",
        requestByCustomer: "Request by Customer",
        pending: "Pending",
        paymentConfirmed: "Payment Confirmed",
        reject: "Reject",
        documentsSubmitted: "Documents Submitted",
        inProgress: "In progress",
        approved: "Approved",
        dispatchedToCustomer: "Dispatched to Customer",
        completed: "Completed",
        rejectNote: "Reject Note",
        confirmDelete: 'Confirm Delete',
        deleteMessage: 'Are you sure you want to delete this record?',
        deleteButton: 'Delete',
        expired: "Expired",
        expiresToday: "Expires Today",
        expiresThisWeek: "Expires This Week",
        expiresThisMonth: "Expires This Month",
         loginTitle: "LOGIN",
        emailPlaceholder: "Email",
        passwordPlaceholder: "Password",
        rememberMe: "Remember me",
        forgotPassword: "Forgot Password?",
        loggingIn: "Logging in...",
        enterYourEmail: "Enter your email",
        enterYourPassword: "Enter your password",
        createdBy: "Created by Techy Solutions",
        roleName: "Role Name",
        enterRoleName: "Enter role name",
        permissions: "Permissions",
        menu: "Menu",
        create: "Create",
        edit: "Edit",
        delete: "Delete",
        export: "Export",
        subcategory:"SubCategory",
        addSubcategory: "Add SubCategory",
        uploadDocuments: 'Attachment Upload',
        remove:'Remove',
        viewDetails:'View Details',
        jobs: "Jobs",
        addJob: "Add Job",
        salary: "Salary",
        description: "Description",
        type:"Type",
    },
    mm: {
        dashboard: "ဒက်ရှ်ဘုတ်",
        myCustomers: "ကျွန်ုပ်၏ Customer များ",
        allCustomers: "Customer အားလုံး",
        customerExpirations: "Customerများ၏ သက်တမ်းကုန်ဆုံးမည့်စာရင်း",
        customerExpiryThisMonth:"ယခုလအတွက် Customerများ၏ သက်တမ်းကုန်ဆုံးမည့်စာရင်း",
        newCustomersThisMonth: "ယခုလအတွက် Customerအသစ်များ",
        activeServiceActivity: "လက်ရှိဝန်ဆောင်မှုလုပ်ဆောင်ချက်များ",
        uploadFromExcel: "Excel မှ စာရင်းထည့်သွင်းခြင်း",
        myServices: "ကျွန်ုပ်၏ ဝန်ဆောင်မှုများ",
        allServices: "ဝန်ဆောင်မှုအားလုံး",
        createService: "ဝန်ဆောင်မှုအသစ်ဖန်တီးရန်",
        createCustomer: "Customer အသစ်ဖန်တီးရန်",
        pleaseTypeCustomerId: "Customer ID ရိုက်ထည့်ပါ",
        customerId: "သုံးစွဲသူ ID",
        nameEng: "အမည် (အင်္ဂလိပ်)",
        nameMm: "အမည် (မြန်မာ)",
        nrcNo: "မှတ်ပုံတင်နံပါတ်",
        prevPassportNo: "ယခင်ပတ်စ်ပို့နံပါတ်",
        passportNo: "ပတ်စ်ပို့နံပါတ်",
        passportExpiryDate: "ပတ်စ်ပို့သက်တမ်းကုန်ရက်",
        visaType: "ဗီဇာအမျိုးအစား",
        visaNumber: "ဗီဇာနံပါတ်",
        visaExpiryDate: "ဗီဇာသက်တမ်းကုန်ရက်",
        detail: "အသေးစိတ်",
        view: "ကြည့်ရန်",
        search: "ရှာဖွေရန်",
        addNewCustomer: "Customer အသစ်ထည့်သွင်းရန်",
        sex: "လိင်",
        dob: "မွေးသက္ကရာဇ်",
        nrc: "မှတ်ပုံတင်နံပါတ်",
        nationality: "နိုင်ငံသား",
        passportDetails: "ပတ်စ်ပို့အချက်အလက်အသေးစိတ်",
        scanPassport: "ပတ်စ်ပို့စကင်ဖတ်ရန်",
        visaDetails: "ဗီဇာအချက်အလက်အသေးစိတ်",
        scanVisa: "ဗီဇာစကင်ဖတ်ရန်",
        ciDetails: "CI အချက်အလက်အသေးစိတ်",
        scanCi: "CI စကင်ဖတ်ရန်",
        ciNo: "CI နံပါတ်",
        ciExpiryDate: "CI သက်တမ်းကုန်ရက်",
        pinkCardDetails: "ပန်းရောင်ကဒ်အချက်အလက်အသေးစိတ်",
        scanPinkCard: "ပန်းရောင်ကဒ်စကင်ဖတ်ရန်",
        pinkCardNo: "ပန်းရောင်ကဒ်နံပါတ်",
        pinkCardExpiryDate: "ပန်းရောင်ကဒ် သက်တမ်းကုန်ရက်",
        phonePrimary: "ဖုန်းနံပါတ် (အဓိက)",
        phoneSecondary: "ဖုန်းနံပါတ် (ဒုတိယ)",
        emailAddress: "အီးမေးလ်လိပ်စာ",
        currentAddress: "လက်ရှိလိပ်စာ",
        save: "သိမ်းဆည်းရန်",
        saving: 'သိမ်းဆည်းနေပါသည်...',
        back: "နောက်သို့",
        editCustomer: "Customer ၏ အချက်အလက်ကိုတည်းဖြတ်ရန်",
        passportExpiry: "ပတ်စ်ပို့သက်တမ်းကုန်ရက်",
        visaExpiry: "ဗီဇာသက်တမ်းကုန်ရက်",
        pinkCardExpiry: "ပန်းရောင်ကဒ် သက်တမ်းကုန်ရက်",
        ciCardExpiry: "CI ကဒ်သက်တမ်းကုန်ရက်",
        addServiceActivity: "ဝန်ဆောင်မှုလုပ်ဆောင်ချက်ထည့်ရန်",
        status: "အခြေ‌အနေ",
        serviceRequestType: "ဝန်ဆောင်မှုတောင်းဆိုသည့်အမျိုးအစား",
        refresh: "ပြန်လည်အစပြုရန်",
        requestDate: "တောင်းဆိုသည့်ရက်",
        requestBy: "တောင်းဆိုသူ",
        chooseCustomer: "Customer ရွေးချယ်ရန်",
        requestType: "တောင်းဆိုမှုအမျိုးအစား",
        serviceStatus: "ဝန်ဆောင်မှုအခြေအနေ",
        customerServiceUrl: "Customer အတွက်ဝန်ဆောင်မှု URL",
        copy: "ကူးယူရန်",
        send: "ပို့ရန်",
        createServiceActivity:"ဝန်ဆောင်မှုလုပ်ဆောင်ချက်အသစ်ဖန်တီးရန်",
        editServiceActivity: "ဝန်ဆောင်မှုလုပ်ဆောင်ချက်တည်းဖြတ်ရန်",
        importCustomers: "သုံးစွဲသူများ၏ အချက်အလက်ကိုတင်သွင်းရန်",
        uploadFile: "ဖိုင်တင်သွင်းရန်",
        format: "ပုံစံ",
        cancel: "ပယ်ဖျက်သည်",
        import: "တင်သွင်းရန်",
        importing: 'တင်သွင်းနေပါသည်...',
        bizName: "လုပ်ငန်းအမည်",
        phoneNumber: "ဖုန်းနံပါတ်",
        location: "နေရပ်လိပ်စာ",
        availableServices: "ရရှိနိုင်သောဝန်ဆောင်မှုများ",
        category: "အမျိုးအစား",
        title: "ခေါင်းစဉ်",
        serviceCost: "ဝန်ဆောင်မှုကုန်ကျစရိတ်",
        serviceDuration: "ဝန်ဆောင်မှုကြာချိန်",
        editService: "ဝန်ဆောင်မှုတည်းဖြတ်ရန်",
        agentId: "အေးဂျင့် ID",
        addAgent: "အေးဂျင့်အသစ်ထည့်သွင်းရန်",
        createAgent: "အေးဂျင့်အသစ်ဖန်တီးရန်",
        editAgent: "အေးဂျင့်တည်းဖြတ်ရန်",
        addCategory: "အမျိုးအစားအသစ်ထည့်သွင်းရန်",
        createCategory: "အမျိုးအစားအသစ်ဖန်တီးရန်",
        editCategory: "အမျိုးအစားတည်းဖြတ်ရန်",
        addUser: "အသုံးပြုသူအသစ်ထည့်သွင်းရန်",
        createUser: "အသုံးပြုသူအသစ်ဖန်တီးရန်",
        editUser: "အသုံးပြုသူတည်းဖြတ်ရန်",
        addRole: "အခန်းကဏ္ဍအသစ်ထည့်သွင်းရန်",
        createRole: "အခန်းကဏ္ဍအသစ်ဖန်တီးရန်",
        editRole: "အခန်းကဏ္ဍတည်းဖြတ်ရန်",
        userSetting: "အသုံးပြုသူ ဆက်တင်",
        logout: "အကောင့်မှထွက်ရန်",
        name: "အမည်",
        email: "အီးမေးလ်",
        password: "လျှို့ဝှက်နံပါတ်",
        confirmPassword: "လျှို့ဝှက်နံပါတ်အတည်ပြုရန်",
        updateProfile: "ကိုယ်ရေးအချက်အလက်ကို အသစ်ထည့်သွင်းရန်",
        leaveBlankPassword: "လက်ရှိလျှို့ဝှက်နံပါတ်အတွက် ဤနေရာကိုလွတ်ထားပါ",
        editProfile: "ကိုယ်ရေးအချက်အလက်ကို တည်းဖြတ်ရန်",
        setup: "အစပြုရန်",
        management: "စီမံခန့်ခွဲမှု",
        categories: "အမျိုးအစားများ",
        roles: "အခန်းကဏ္ဍများ",
        users: "အသုံးပြုသူများ",
        agents: "အေးဂျင့်များ",
        totalAgents: "စုစုပေါင်းအေးဂျင့်များ",
        agentsThisMonth: "ယခုလအတွက် အေးဂျင့်များ",
        totalCustomers: "စုစုပေါင်းCustomerများ",
        customersThisMonth: "ယခုလအတွက် Customerများ",
        language: "ဘာသာစကား",
        welcomeEpsSystem: "Logistic",
        login: "အကောင့်ဝင်ရန်",
        requestByCustomer: "သုံးစွဲသူမှတောင်းဆိုမှု",
        pending: "ဆိုင်းငံ့ထားဆဲ",
        paymentConfirmed: "ငွေပေးချေမှုအတည်ပြုပြီး",
        reject: "ပယ်ချသည်",
        documentsSubmitted: "စာရွက်စာတမ်းများတင်ပြီး",
        inProgress: "ဆောင်ရွက်ဆဲ",
        approved: "အတည်ပြုပြီး",
        dispatchedToCustomer: "Customerထံသို့ပို့ပြီး",
        completed: "ပြီးစီးသည်",
        rejectNote: "ပယ်ချသည့်မှတ်ချက်",
        confirmDelete: 'ဖျက်ရန်အတည်ပြုမည်',
        deleteMessage: 'ဤမှတ်တမ်းကို ဖျက်လိုသည်မှာ သေချာပါသလား?',
        deleteButton: 'ဖျက်မည်',
        expired: "သက်တမ်းကုန်ဆုံးပြီး",
        expiresToday: "ယနေ့ကုန်ဆုံးမည်",
        expiresThisWeek: "ဤသီတင်းပတ်အတွင်းကုန်ဆုံးမည်",
        expiresThisMonth: "ဤလအတွင်းကုန်ဆုံးမည်",
        loginTitle: "အကောင့်ဝင်ပါ",
        emailPlaceholder: "အီးမေးလ်",
        passwordPlaceholder: "လျှို့ဝှက်နံပါတ်",
        rememberMe: "မှတ်ထားပါ",
        forgotPassword: "စကားဝှက်မေ့နေပါသလား?",
        loggingIn: "ဝင်နေပါသည်...",
        enterYourEmail: "သင့်အီးမေးလ်ထည့်ပါ",
        enterYourPassword: "သင့်စကားဝှက်ထည့်ပါ",
        createdBy: "Techy Solutions မှ ဖန်တီးထားသည်",
        roleName: "ရာထူးအမည်",
        permissions: "ခွင့်ပြုချက်များ",
        menu: "မီနူး",
        create: "ဖန်တီးရန်",
        edit: "ပြင်ဆင်ရန်",
        delete: "ဖျက်ရန်",
        export: "တင်ပို့ရန်",
        subcategory:"အမျိုးအစားခွဲ",
        addSubcategory: "အမျိုးအစားခွဲထည့်ရန်",
        uploadDocuments: 'ဖိုင်တင်ခြင်း',
        remove: 'ဖျက်ရန်',
        viewDetails:'အသေးစိတ်ကြည့်ရန်',
        jobs: "အလုပ်များ",
        addJob: "အလုပ်အသစ် ထည့်ရန်",
        salary: "လစာ",
        description: "ဖော်ပြချက်",
        type:"အမျိုးအစား",
    }
};
