<?php

    return [
        'statuses' => [
            ['label' => 'Active', 'value' => 1],
            ['label' => 'Inactive', 'value' => 0],
        ],
        'modes' => [
            ['label' => 'Air', 'value' => 1],
            ['label' => 'Sea', 'value' => 2],
            ['label' => 'Transport', 'value' => 3],
        ],
        'customer_types' => [
            ['label' => 'Individual', 'value' => 1],
            ['label' => 'Corporate', 'value' => 2],
        ],
        'checkpoint_types' => [
            ['label' => 'Start', 'value' => 'start'],
            ['label' => 'Toll', 'value' => 'toll'],
            ['label' => 'Customs', 'value' => 'customs'],
            ['label' => 'End', 'value' => 'end'],
        ],
        'categories' => [
            ['label' => 'Export', 'value' => 1],
            ['label' => 'Import', 'value' => 2],
        ],
        'lead_statuses' => [
            ['label' => 'Confirm', 'value' => 1],
            ['label' => 'Pending', 'value' => 0],
        ],
        'loading_ports' => [
            ['label' => 'BBK SLT', 'value' => 1],
            ['label' => 'DUBAI', 'value' => 2],
            ['label' => 'HAI PHONG PORT, VIETNAM', 'value' => 3],
            ['label' => 'HO CHI MINH PORT, VIETNAM', 'value' => 4],
            ['label' => 'HONG KONG', 'value' => 5],
            ['label' => 'Huaykwang', 'value' => 6],
            ['label' => 'JAKARTA', 'value' => 7],
            ['label' => 'JIUJIANG, CHINA', 'value' => 8],
            ['label' => 'KLANG, MALAYSIA', 'value' => 9],
            ['label' => 'KOLKATA, INDIA', 'value' => 10],
            ['label' => 'MUNDRA, INDIA', 'value' => 11],
            ['label' => 'NANSHA, CHINA', 'value' => 12],
            ['label' => 'NANSHA (GD)', 'value' => 13],
            ['label' => 'NANSHA NEW PORT', 'value' => 14],
            ['label' => 'NHAVA SHEVA, INDIA', 'value' => 15],
            ['label' => 'NINGBO, CHINA', 'value' => 16],
            ['label' => 'NINGBO, CHINA 2', 'value' => 17],
            ['label' => 'PORT KLANG, MALAYSIA', 'value' => 18],
            ['label' => 'QINGDAO', 'value' => 19],
            ['label' => 'QINGDAO, CHINA', 'value' => 20],
            ['label' => 'SAMUT PRAKAN', 'value' => 21],
            ['label' => 'SAMUT SAKHON', 'value' => 22],
            ['label' => 'SHANGHAI, CHINA', 'value' => 23],
            ['label' => 'SHEKOU, CHINA', 'value' => 24],
            ['label' => 'SHEKOU, GUANGDONG, CHINA', 'value' => 25],
            ['label' => 'SHENZHEN, CHINA', 'value' => 26],
            ['label' => 'SINGAPORE', 'value' => 27],
            ['label' => 'SRITHAI', 'value' => 28],
            ['label' => 'TIANJIN, CHINA', 'value' => 29],
            ['label' => 'XI NGANG, CHINA', 'value' => 30],
            ['label' => 'XIAMEN, CHINA', 'value' => 31],
            ['label' => 'XINGANG, CHINA', 'value' => 32],
            ['label' => 'XINGANG, TIANJIN', 'value' => 33],
            ['label' => 'XINGANG, TIANJIN, CHINA', 'value' => 34],
            ['label' => 'YANTIAN, CHINA', 'value' => 35],
            ['label' => 'YOKOHAMA', 'value' => 36],
            ['label' => 'ZHANJIANG, CHINA', 'value' => 37],
        ],
        'discharge_ports' => [
            ['label' => 'Laem Chabang Port', 'value' => 1],
        ], 
        'cariers' => [
            ['label' => 'A PLUS', 'value' => 1],
            ['label' => 'ALPINE SHIPPING', 'value' => 2],
            ['label' => 'AMASS', 'value' => 3],
            ['label' => 'ASEAN SEAS LINE', 'value' => 4],
            ['label' => 'AUSTERE LOGISTICS', 'value' => 5],
            ['label' => 'AWS CONTAINER LINE', 'value' => 6],
            ['label' => 'CHARTER LINK LOGISTICS', 'value' => 7],
            ['label' => 'CK LINE', 'value' => 8],
            ['label' => 'CMA CGM', 'value' => 9],
            ['label' => 'CNC', 'value' => 10],
            ['label' => 'COSCO', 'value' => 11],
            ['label' => 'CSL', 'value' => 12],
            ['label' => 'CU LINES', 'value' => 13],
            ['label' => 'DANMAR LINES', 'value' => 14],
            ['label' => 'DHL GLOBAL FORWARDING', 'value' => 15],
            ['label' => 'ELAN LOGISTICS', 'value' => 16],
            ['label' => 'ELAN LOGISTICS PTE LTD', 'value' => 17],
            ['label' => 'EVERGREEN LINE', 'value' => 18],
            ['label' => 'GATEWAY CONTAINER LINE', 'value' => 19],
            ['label' => 'GOLD STAR LINE', 'value' => 20],
            ['label' => 'Hapag-Lloyd', 'value' => 21],
            ['label' => 'HAZEL WRIGHTS LOGISTICS PTE LTD', 'value' => 22],
            ['label' => 'HEUNG A LINE', 'value' => 23],
            ['label' => 'HMM', 'value' => 24],
            ['label' => 'I CARRY CONTAINERS PTE LTD', 'value' => 25],
            ['label' => 'IFL INTERNATIONAL FREIGHT LINE', 'value' => 26],
            ['label' => 'INOX SHIPPING', 'value' => 27],
            ['label' => 'INTERASIA', 'value' => 28],
            ['label' => 'JGL Worldwide (SG) Pte. Ltd.', 'value' => 29],
            ['label' => 'KMTC', 'value' => 30],
            ['label' => 'KNOT GLOBAL HOLDINGS CO., LTD', 'value' => 31],
            ['label' => 'MAERSK', 'value' => 32],
            ['label' => 'MAXICON CONTAINER LINE', 'value' => 33],
            ['label' => 'MCC CONTAINER LINE', 'value' => 34],
            ['label' => 'MSC', 'value' => 35],
            ['label' => 'MULTIMODLE TRANSPORT', 'value' => 36],
            ['label' => 'MUSKAN GROUP', 'value' => 37],
            ['label' => 'NAMSUNG SHIPPING', 'value' => 38],
            ['label' => 'NAVIS CONTAINER LINE', 'value' => 39],
            ['label' => 'NINGBO OCEAN SHIPPING CO.,LTD', 'value' => 40],
            ['label' => 'NWL', 'value' => 41],
            ['label' => 'OCEANBLU LINE', 'value' => 42],
            ['label' => 'ONE LINE', 'value' => 43],
            ['label' => 'OOCL', 'value' => 44],
            ['label' => 'PACIFIC INTERNATIONAL LINES', 'value' => 45],
            ['label' => 'PIL', 'value' => 46],
            ['label' => 'POCO SHIPPING', 'value' => 47],
            ['label' => 'PORTEVER SHIPPING', 'value' => 48],
            ['label' => 'RCL', 'value' => 49],
            ['label' => 'RYSE XIM', 'value' => 50],
            ['label' => 'SAMUDERA', 'value' => 51],
            ['label' => 'SHANGHAI JJ SHIPPING', 'value' => 52],
            ['label' => 'SHENZHEN SUNNY SUPPLY', 'value' => 53],
            ['label' => 'SINO LINES', 'value' => 54],
            ['label' => 'SINOTRANS LINES', 'value' => 55],
            ['label' => 'SITC', 'value' => 56],
            ['label' => 'SNG FREIGHT THAILAND', 'value' => 57],
            ['label' => 'T.G LINE', 'value' => 58],
            ['label' => 'TCLC', 'value' => 59],
            ['label' => 'TMC', 'value' => 60],
            ['label' => 'TS LINES', 'value' => 61],
            ['label' => 'VISTAR SHIPPING', 'value' => 62],
            ['label' => 'WAN HAI', 'value' => 63],
            ['label' => 'World Jaguar Logistics Inc.', 'value' => 64],
            ['label' => 'WWP', 'value' => 65],
            ['label' => 'YANG MING', 'value' => 66],
            ['label' => 'ZIM', 'value' => 67],
            ['label' => 'VASCO MARITIME PTE LTD', 'value' => 68],
        ], 
        'consignee_names' => [
            ['label' => 'AIMA MYANMAR COMPANY LIMITED', 'value' => 1],
            ['label' => 'AUNG KAN BO CO., LTD', 'value' => 2],
            ['label' => 'ECO SHINE TRADING CO., LTD', 'value' => 3],
            ['label' => 'ETERNAL GOLD CO., LTD', 'value' => 4],
            ['label' => 'EVER SUNNY INDUSTRIAL CO., LTD', 'value' => 5],
            ['label' => 'GENERAL DRUG HOUSE CO., LTD', 'value' => 6],
            ['label' => 'INFINITY BUSINESS GROUP CO., LTD', 'value' => 7],
            ['label' => 'LA POWER COMPANY LIMITED', 'value' => 8],
            ['label' => 'LIFE TRUST INTERNATIONAL CO., LTD', 'value' => 9],
            ['label' => 'MEGA ONE TRADING CO. LTD.', 'value' => 10],
            ['label' => 'MELBOURNE COMPANY LIMITED', 'value' => 11],
            ['label' => 'MYO THEIN ELECTRONIC CO., LTD', 'value' => 12],
            ['label' => 'ONMAX CO., LTD', 'value' => 13],
            ['label' => 'PHYO KYAWE YADANAR COMPANY LIMITED', 'value' => 14],
            ['label' => 'POWER GLOBAL IMPEX COMPANY LIMITED', 'value' => 15],
            ['label' => 'RAINFORCE IMPERIOR COMPANY LIMITED', 'value' => 16],
            ['label' => 'SB BABY CO., LTD', 'value' => 17],
            ['label' => 'SHANG HAI COSMETIC CO., LTD', 'value' => 18],
            ['label' => 'SHWE NGWE TOE CO., LTD', 'value' => 19],
            ['label' => 'SUGO INTERNATIONAL TRADING COMPANY LIMITED', 'value' => 20],
            ['label' => 'SUPER MYINTMO COMPANY LIMITED', 'value' => 21],
            ['label' => 'THINZAR KYAW PRODUCTION CO., LTD', 'value' => 22],
            ['label' => 'UNITED CENTUS CO., LTD', 'value' => 23],
            ['label' => 'UNITED CHAN THAR CO., LTD', 'value' => 24],
            ['label' => 'WEALTHY MYANMAR CO., LTD', 'value' => 25],
            ['label' => 'WIN YADANAR BON CO., LTD', 'value' => 26],
            ['label' => 'SUPER LIGHT LOGISTICS (THAILAND) CO.,LTD','value'=>27],
            ['label' => 'DIXO TECH ENERGY SOLUTIONS COMPANY LIMITED','value'=>28],
        ],

        'shipment_types' => [
            ['label' => 'Transit', 'value' => 1],
            ['label' => 'FreeZone', 'value' => 2],
            ['label' => 'Transport', 'value' => 3],
        ],

        'bl_statuses' => [
            ['label' => 'Seaway Bill', 'value' => 1],
            ['label' => 'Surrendered', 'value' => 2],
            ['label' => 'OPL', 'value' => 3],
        ],
        'free_day_types' => [
            ['label' => 'Combined', 'value' => 1],
            ['label' => 'Separate', 'value' => 2],
        ],
        'container_types' => [
            ['label' => '20 Ft', 'value' => 1],
            ['label' => '40 Ft', 'value' => 2],
            ['label' => '20 Ft(Part Load)', 'value' => 3],
            ['label' => '40 Ft(Part Load)', 'value' => 4],
            ['label' => 'LCL', 'value' => 5],
        ],
       'uoms' => [
            ['label' => 'Cartons', 'value' => 1],
            ['label' => 'Pallets', 'value' => 2],
            ['label' => 'Pkgs', 'value' => 3],
            ['label' => 'Rolls', 'value' => 4],
            ['label' => 'Boxes', 'value' => 5],
            ['label' => 'Pcs', 'value' => 6],
            ['label' => 'Bags', 'value' => 7],
            ['label' => 'Bales', 'value' => 8],
            ['label' => 'Cans', 'value' => 9],
        ],
        'fz_options' => [
            ['label' => 'EA', 'value' => 1],
            ['label' => 'EG', 'value' => 2],
            ['label' => 'FERRY', 'value' => 3],
            ['label' => 'KLN', 'value' => 4],
            ['label' => 'KPPS', 'value' => 5],
            ['label' => 'SPEED', 'value' => 6],
            ['label' => 'Srithai DC', 'value' => 7],
            ['label' => 'Srithai NB', 'value' => 8],
            ['label' => 'WHALE', 'value' => 9],
            ['label' => 'LCB2-FZ1/4', 'value' => 10],
            ['label' => 'LCB2-FZ1/5', 'value' => 11],
        ],
        'job_statuses' => [
            ['label' => 'Pending', 'value' => 0],
            ['label' => 'Approved', 'value' => 1],
            ['label' => 'Completed', 'value' => 2],
        ],
       'trip_statuses' => [
            ['label' => 'Pending', 'label_th' => 'รอดำเนินการ', 'value' => 0],
            ['label' => 'Accepted', 'label_th' => 'ยอมรับ', 'value' => 1],
            ['label' => 'Arrived Port', 'label_th' => 'ถึงท่าเรือ', 'value' => 2],
            ['label' => 'Cargo Loaded', 'label_th' => 'โหลดสินค้า', 'value' => 3],
            ['label' => 'Left Port', 'label_th' => 'ออกจากท่าเรือ', 'value' => 4],
            ['label' => 'On Route', 'label_th' => 'อยู่บนเส้นทาง', 'value' => 5],
            ['label' => 'Arrived Destination', 'label_th' => 'ถึงจุดหมายปลายทาง', 'value' => 6],
            ['label' => 'Left Destination', 'label_th' => 'ออกจากปลายทาง', 'value' => 7],
            ['label' => 'Container Return', 'label_th' => 'คืนตู้เปล่า', 'value' => 8],
            ['label' => 'Trip Ended', 'label_th' => 'การส่งสินค้าเสร็จเสิ้น', 'value' => 9],
            ['label' => 'Expense Added', 'label_th' => 'เพิ่มค่าใช้จ่าย', 'value' => 10],
        ],
        'container_statuses' => [
            ['label' => 'Pending', 'value' => 0],
            ['label' => 'Assigned', 'value' => 1],
            ['label' => 'Completed', 'value' => 2],
        ],
        'expense_types' => [
            ['label' => 'Advance - Truck Drivers (Advance Paid to Driver)', 'label_th' => 'เงินล่วงหน้า -(จ่ายเงินล่วงหน้าให้คนขับ)', 'value' => 1],
            ['label' => 'Guarantee Money (Driver Deposit Deduction)', 'label_th' => 'เงินประกัน (หักจากเงินมัดจำของคนขับ)', 'value' => 2],
            ['label' => 'Border Pass', 'label_th' => 'ผ่านแดน', 'value' => 3],
            ['label' => 'Cabinet Return', 'label_th' => 'คืนตู้เปล่า', 'value' => 4],
            ['label' => 'Container Cleaning', 'label_th' => 'การทำความสะอาดตู้คอนแทนเนอร์', 'value' => 5],
            ['label' => 'Courier Charges', 'label_th' => 'ค่าบริการจัดส่งพัสดุ', 'value' => 6],
            ['label' => 'Document & License', 'label_th' => 'ค่เอกสารและใบอนุญาต', 'value' => 7], 
            ['label' => 'Driving Fee', 'label_th' => 'ค่าเที่ยว', 'value' => 8],
            ['label' => 'Fuel Charges', 'label_th' => 'ค่าน้ำมัน', 'value' => 9],
            ['label' => 'Gate Fee', 'label_th' => 'ค่าผ่านท่า', 'value' => 10],
            ['label' => 'Toll Charges', 'label_th' => 'ค่าผ่านทาง', 'value' => 11],
            ['label' => 'Hotel Myanmar Side', 'label_th' => 'โรงแรมฝั่งเมียนมาร์', 'value' => 12],
            ['label' => 'Labour Charge', 'label_th' => 'ค่าแรงงาน', 'value' => 13],
            ['label' => 'Lift Off', 'label_th' => 'ยกตู้ลง', 'value' => 14],
            ['label' => 'Lift On', 'label_th' => 'ยกคู้ขึ้น', 'value' => 15],
            ['label' => 'Loading', 'label_th' => 'โหลดสินค้า', 'value' => 16],
            ['label' => 'Night Stop Fee', 'label_th' => 'ค่าแวะพักกลางคืน', 'value' => 17],
            ['label' => 'OT', 'label_th' => 'โอที', 'value' => 18],
            ['label' => 'Police fine', 'label_th' => 'ตำรวจสบายดี', 'value' => 19],          
            ['label' => 'Port Entrance', 'label_th' => 'ค่าเข้าท่า', 'value' => 20],
            ['label' => 'Repair Fee', 'label_th' => 'ค่าซ่อมตู้', 'value' => 21],
            ['label' => 'Truck Parking Fee', 'label_th' => 'ค่าจอดรถบรรทุก', 'value' => 22],
            ['label' => 'Thai - Myanmar Bridge', 'label_th' => 'สะพานไทย-พม่า', 'value' => 23],
            ['label' => 'Empaty Container Rrturn Fee', 'label_th' => 'ค่าคืนตู้เปล่า', 'value' => 24],
            ['label' => 'Weighting Fee', 'label_th' => 'ค่าชั่งน้ำหนัก', 'value' => 25],
            ['label' => 'Others', 'label_th' => 'อื่นๆ', 'value' => 26],
        ],
        'income_titles' => [
            ['label' => 'Cabinet Return', 'value' => 1],
            ['label' => 'Container Cleaning', 'value' => 2],
            ['label' => 'Container Deposit', 'value' => 3],
            ['label' => 'Container Repair', 'value' => 4],
            ['label' => 'Courier Charges', 'value' => 5],
            ['label' => 'Custom Clearance : AF', 'value' => 6],
            ['label' => 'Custom Clearance : FZ (TG)', 'value' => 7],
            ['label' => 'Custom Clearance : FZ Direct', 'value' => 8],
            ['label' => 'Custom Clearance : Re-import', 'value' => 9],
            ['label' => 'Custom Clearance : SF', 'value' => 10],
            ['label' => 'Custom Clearance (Extra)', 'value' => 11],
            ['label' => 'Demurrage', 'value' => 12],
            ['label' => 'Detention', 'value' => 13],
            ['label' => 'Export Formalities', 'value' => 14],
            ['label' => 'Export Service', 'value' => 15],
            ['label' => 'Extra DO Fees', 'value' => 16],
            ['label' => 'Gate Fee', 'value' => 17],
            ['label' => 'Handling In-Out : FZ', 'value' => 18],
            ['label' => 'Handling In-Out : General WH', 'value' => 19],
            ['label' => 'Lift Off', 'value' => 20],
            ['label' => 'Lift On', 'value' => 21],
            ['label' => 'LSS', 'value' => 22],
            ['label' => 'Management Fee', 'value' => 23],
            ['label' => 'Overtime Charges', 'value' => 24],
            ['label' => 'Pallet Rental', 'value' => 25],
            ['label' => 'Port Charges', 'value' => 26],
            ['label' => 'Port Customs Fine', 'value' => 27],
            ['label' => 'Port Entrance', 'value' => 28],
            ['label' => 'Port Export Clearance', 'value' => 29],
            ['label' => 'Refund Processing Charges', 'value' => 30],
            ['label' => 'Shipping Charge', 'value' => 31],
            ['label' => 'Storage Charge : FZ', 'value' => 32],
            ['label' => 'Storage Charge : General WH', 'value' => 33],
            ['label' => 'Surcharge', 'value' => 34],
            ['label' => 'Terminal Customs Fine', 'value' => 35],
            ['label' => 'Transportation Service', 'value' => 36],
            ['label' => 'Truck Detention Charge', 'value' => 37],
            ['label' => 'Truck Parking', 'value' => 38],
            ['label' => 'Truck Rental', 'value' => 39],
            ['label' => 'VAS', 'value' => 40],
            ['label' => 'Revenue', 'value' => 41],
            ['label' => 'Others', 'value' => 99],
        ],
        'expense_titles' => [
            ['label' => 'Agricultural', 'value' => 1],
            ['label' => 'Amendent Charges', 'value' => 2],
            ['label' => 'BL Amend Fees', 'value' => 3],
            ['label' => 'Border Pass', 'value' => 4],
            ['label' => 'Cabinet Return', 'value' => 5],
            ['label' => 'CCM Service Fee', 'value' => 6],
            ['label' => 'Clerk Wage & Meal', 'value' => 7],
            ['label' => 'Container Cleaning', 'value' => 8],
            ['label' => 'Container Rental', 'value' => 9],
            ['label' => 'Container Repair', 'value' => 10],
            ['label' => 'Container Return', 'value' => 11],
            ['label' => 'Courier Charges', 'value' => 12],
            ['label' => 'Crane Rental', 'value' => 13],
            ['label' => 'Custom Clearance : AF', 'value' => 14],
            ['label' => 'Custom Clearance : FZ (TG)', 'value' => 15],
            ['label' => 'Custom Clearance : FZ Direct', 'value' => 16],
            ['label' => 'Custom Clearance : Re-import', 'value' => 17],
            ['label' => 'Custom Clearance (Extra)', 'value' => 18],
            ['label' => 'Customs Fee', 'value' => 19],
            ['label' => 'Demurage', 'value' => 20],
            ['label' => 'Detention', 'value' => 21],
            ['label' => 'DO Charges', 'value' => 22],
            ['label' => 'Export Service', 'value' => 23],
            ['label' => 'Express Way Toll Fee', 'value' => 24],
            ['label' => 'Extra DO Fees', 'value' => 25],
            ['label' => 'Forklift Rental', 'value' => 26],
            ['label' => 'Fuel', 'value' => 27],
            ['label' => 'Handling In-Out : FZ', 'value' => 28],
            ['label' => 'Handling In-Out : General WH', 'value' => 29],
            ['label' => 'Inspection Fee', 'value' => 30],
            ['label' => 'Labour Charge', 'value' => 31],
            ['label' => 'Lift Off', 'value' => 32],
            ['label' => 'Lift On', 'value' => 33],
            ['label' => 'LSS', 'value' => 34],
            ['label' => 'Night Stop', 'value' => 35],
            ['label' => 'Pallet Rental', 'value' => 36],
            ['label' => 'Permit (Cross-Border)', 'value' => 37],
            ['label' => 'Permit (Port)', 'value' => 38],
            ['label' => 'Police Fine', 'value' => 39],
            ['label' => 'Port Charges', 'value' => 40],
            ['label' => 'Port Clearance Charge', 'value' => 41],
            ['label' => 'Port Customs Fine', 'value' => 42],
            ['label' => 'Port Entrance', 'value' => 43],
            ['label' => 'Ranong Operation Charge', 'value' => 44],
            ['label' => 'Refund Processing Charges', 'value' => 45],
            ['label' => 'Repair', 'value' => 46],
            ['label' => 'Shipping Charge', 'value' => 47],
            ['label' => 'Stevedoring Service', 'value' => 48],
            ['label' => 'Storage Charge : FZ', 'value' => 49],
            ['label' => 'Storage Charge : General WH', 'value' => 50],
            ['label' => 'Surcharge', 'value' => 51],
            ['label' => 'Terminal Charges', 'value' => 52],
            ['label' => 'Terminal Customs Fine', 'value' => 53],
            ['label' => 'VAS', 'value' => 54],
            ['label' => 'X-Ray', 'value' => 55],
            ['label' => 'Others', 'value' => 99],
        ], 
        'incoming_report_calculated_by' => [
            ['label' => 'ATA', 'value' => 1],
            ['label' => 'ETA', 'value' => 2],
        ],           
        'paginate_per_page' => 10,
    ];

